name: build

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/Semcosm.HardwareConsole.App/Semcosm.HardwareConsole.App.csproj -p:Platform=x64

      - name: Build
        run: dotnet build src/Semcosm.HardwareConsole.App/Semcosm.HardwareConsole.App.csproj --configuration Debug --no-restore -p:Platform=x64
